export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_ERROR =   "GET_USER_DETAILS_ERROR";

export const POST_USER_DETAILS_REQUEST = "POST_USER_DETAILS_REQUEST";
export const POST_USER_DETAILS_SUCCESS = "POST_USER_DETAILS_SUCCESS";
export const POST_USER_DETAILS_ERROR = "POST_USER_DETAILS_ERROR";
