export const GET_ADMINDATA_REQUEST = 'GET_ADMINDATA_REQUEST'
export const GET_ADMINDATA_SUCCESS = 'GET_ADMINDATA_SUCCESS'
export const GET_ADMINDATA_ERROR = 'GET_ADMINDATA_ERROR'

export const DELETE_ADMIN_DATA_REQUEST = 'DELETE_ADMIN_DATA_REQUEST'
export const DELETE_ADMIN_DATA_SUCCESS = 'DELETE_ADMIN_DATA_SUCCESS'
export const DELETE_ADMIN_DATA_ERROR = 'DELETE_ADMIN_DATA_ERROR'

export const POST_ADMIN_DATA_REQUEST = 'POST_ADMIN_DATA_REQUEST'
export const POST_ADMIN_DATA_SUCCESS = 'POST_ADMIN_DATA_SUCCESS'
export const POST_ADMIN_DATA_ERROR = 'POST_ADMIN_DATA_ERROR'

export const EDIT_ADMIN_DATA_REQUEST = 'EDIT_ADMIN_DATA_REQUEST'
export const EDIT_ADMIN_DATA_SUCCESS = 'EDIT_ADMIN_DATA_SUCCESS'
export const EDIT_ADMIN_DATA_ERROR =   'EDIT_ADMIN_DATA_ERROR'


