export const GET_USERDATA_REQUEST = 'GET_USERDATA_REQUEST'
export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS'
export const GET_USERDATA_ERROR =   'GET_USERDATA_ERROR'

export const POST_USER_DATA_REQUEST = 'POST_USER_DATA_REQUEST'
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS'
export const POST_USER_DATA_ERROR =   'POST_USER_DATA_ERROR'

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST'
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS'
export const USER_SEARCH_ERROR = 'USER_SEARCH_ERROR'

export const BUY_REQUEST = 'BUY_REQUEST'
export const BUY_SUCCESS = 'BUY_SUCCESS'
export const BUY_ERROR =   'BUY_ERROR'