import mock1 from '../assets/mock1.png';
import mock2 from '../assets/mock2.png'
import mock3 from '../assets/mock3.png';
import mock4 from '../assets/mock4.png';
import pokemon from '../assets/pokemon.png';
import weather from '../assets/weather.png';
import social from '../assets/social.png';
import snake from '../assets/snake.png';
import tictac from '../assets/tictac.png';
import library from '../assets/library.png';
import mock7 from '../assets/mock7.png'
import mock8 from '../assets/mock8.png'
import mock9 from '../assets/mock9.png'
import youtube from '../assets/youtube.png'
import shoe from '../assets/shoe.png'
import blog from '../assets/blog.png'
import playo from "../assets/playo.png"
import trav2 from "../assests/trav2.png"
export default {mock1,playo,mock2,mock3,mock4,pokemon,weather,social,snake,tictac,library,mock7,mock8,mock9,youtube,shoe,blog,trav2}
