export const QUIZ_DETAILS_SUCCESS = 'QUIZ_DETAILS_SUCCESS'
export const QUIZ_DETAILS_ERROR  = 'QUIZ_DETAILS_ERROR'
export const QUIZ_DETAILS_REQUEST = 'QUIZ_DETAILS_REQUEST'

export const GET_QUS_REQUEST = "GET_QUS_REQUEST";
export const GET_QUS_SUCCESS = "GET_QUS_SUCCESS"
export const GET_QUS_ERROR = "GET_QUS_ERROR"

export const POST_SCORE_REQUST = 'POST_SCORE_REQUST' ;
export const POST_SCORE_SUCCESS = 'POST_SCORE_SUCCESS' ;
export const POST_SCORE_ERROR = 'POST_SCORE_ERROR' ;
